### ISSUE TITLE
Not working in Android 14

### ISSUE THREAD

**Issue by alr86** [ralismark/bluehid#8]
When I open it in android 14, Immediately get crash with this crash log: https://paste.crdroid.net/Y0FuKl
```
time: 1732258190268
msg: java.lang.ClassNotFoundException: android.bluetooth.BluetoothInputHost
stacktrace: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/bluetooth/BluetoothInputHost;
	at io.github.ralismark.bluehid.MainActivity$1.onServiceConnected(MainActivity.java:102)
	at android.bluetooth.BluetoothAdapter$ProfileConnection.connect(BluetoothAdapter.java:924)
	at android.bluetooth.BluetoothAdapter.lambda$getProfileProxy$0(BluetoothAdapter.java:3755)
	at android.bluetooth.BluetoothAdapter.$r8$lambda$hVDf6ETlKaEPiQ6OcMRJtNWsJSg(Unknown Source:0)
	at android.bluetooth.BluetoothAdapter$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
Caused by: java.lang.ClassNotFoundException: android.bluetooth.BluetoothInputHost
	... 13 more

```

**Comment by ralismark** [comment]
Try the `android-p` branch. `master` was intended for using the hidden APIs from before Android P

**Comment by Maxmatch** [comment]
> Try the `android-p` branch. `master` was intended for using the hidden APIs from before Android P

is it in releases or I should compile it?
